# Generated by Django 3.0.2 on 2020-01-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(default=''),
        ),
    ]
