# Generated by Django 3.0.2 on 2020-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(default=None),
        ),
    ]
