# Generated by Django 3.0.2 on 2020-01-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200118_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
