# Generated by Django 3.0.2 on 2020-01-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200128_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'current_page', 'total_pages', 'list_of_books')},
        ),
    ]
