# Generated by Django 3.0.2 on 2020-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200118_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListfOfBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
