# Generated by Django 3.0.2 on 2020-01-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200128_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='list_of_books',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.ListfOfBooks'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
