# Generated by Django 3.0.2 on 2020-01-21 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_list_of_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='list_of_books',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.ListfOfBooks'),
        ),
    ]
