# Generated by Django 3.0.2 on 2020-01-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200128_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'list_of_books')},
        ),
    ]
