# Generated by Django 3.0.2 on 2020-01-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200128_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='list_of_books',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.ListfOfBooks'),
        ),
    ]
